name: "📝 Test Case Template"
description: Detail the steps necessary to perform a specific test case within the OSRD application.
title: "[TEST]"
labels: 
  - kind:test-case
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this test case template!
        Please provide detailed steps and expected outcomes to help ensure thorough testing.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Brief description of what this test case is intended to verify. Include what part of the application it is testing.
      placeholder: "e.g., Ce cas de test vérifie la création d'une étude."
    validations:
      required: true

  - type: textarea
    id: preconditions
    attributes:
      label: Preconditions
      description: |
        List any conditions or setup that must be done before executing this test case.
      placeholder: "e.g., Les points remarquables sont bien importés."
    validations:
      required: false

  - type: textarea
    id: test_data
    attributes:
      label: Test Data
      description: Specify the data values needed for executing this test.
      placeholder: "e.g., Matériel roulant: TGV"
    validations:
      required: false

  - type: textarea
    id: steps_and_results
    attributes:
      label: Steps and Expected Results
      description: |
        Please describe all the steps of the test case and their expected results in the table format provided below. Use numbering for each step and clearly specify the expected outcome for each.
      placeholder: |
        | Step | Expected Result |
        |------|-----------------|
        | Naviguer vers la section spécifiée de l'application. | La page ou section appropriée se charge avec succès. |
        | Effectuer une action spécifique (par exemple, cliquer sur un bouton, entrer des informations dans un champ de formulaire). | L'action entraîne un changement ou une mise à jour spécifique, tel qu'un nouveau formulaire apparaissant ou un message de confirmation s'affichant. |
        | Entrer ou sélectionner les informations requises (décrire quel type d'information ou où la sélectionner). | Les informations entrées ou sélectionnées sont correctement affichées ou acceptées par l'application. |
        | Soumettre ou sauvegarder les modifications (préciser la méthode ou le bouton utilisé). | Les données sont enregistrées ou soumises comme prévu, et l'utilisateur est dirigé vers la page suivante correcte ou un message de succès est affiché. |
        | Vérifier le résultat (décrire ce qui devrait être vérifié pour s'assurer que l'étape a été réussie). | Les changements attendus sont visibles et aucune erreur n'est présentée. |
    validations:
      required: true

  - type: textarea
    id: notes
    attributes:
      label: Notes
      description: |
        Any additional information that testers need to know, such as special configurations, environment-specific instructions, etc.
      placeholder: "ex., Assurez-vous d'effacer les cookies avant de commencer le test."
    validations:
      required: false

  - type: textarea
    id: references
    attributes:
      label: References
      description: |
        Links to the related documents, tickets, user stories, etc.
      placeholder: "e.g., User Story #123"
    validations:
      required: true
