name: "📝 Test Case Template"
description: Detail the steps necessary to perform a specific test case within the OSRD application.
labels: kind:test-case
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this test case template!
        Please provide detailed steps and expected outcomes to help ensure thorough testing.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Brief description of what this test case is intended to verify. Include what part of the application it is testing.
    validations:
      required: true

  - type: textarea
    id: preconditions
    attributes:
      label: Preconditions
      description: |
        List any conditions or setup that must be done before executing this test case.
      placeholder: "e.g., Les points remarquables sont bien importés."
    validations:
      required: false

  - type: textarea
    id: test_data
    attributes:
      label: Test Data
      description: Specify the data values needed for executing this test.
      placeholder: "e.g., Matériel roulant: TGV"
    validations:
      required: false

- type: textarea
  id: steps_and_results
  attributes:
    label: Steps and Expected Results
    description: Describe all the steps of the test case and their expected results. Use numbering for each step and specify the expected outcome.
    placeholder: |
      1. Step: Go to 'Études d'exploitation'.
         Expected Result: The operational studies page is displayed.
      2. Step: Perform the next action.
         Expected Result: Describe the expected result after performing the action.
      3. Step: Add more steps as needed.
         Expected Result: Describe the expected result for each step.
  validations:
    required: true


  - type: textarea
    id: notes
    attributes:
      label: Notes
      description: |
        Any additional information that testers need to know, such as special configurations, environment-specific instructions, etc.
    validations:
      required: false

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Details about the environment where the test was executed (OS, browser, etc.)
      placeholder: |
        - **Browser**: Chrome v90
        - **OS**: Windows 10
        - **Environment**: Staging
    validations:
      required: false

  - type: textarea
    id: references
    attributes:
      label: References
      description: |
        Links to the related documents, tickets, user stories, etc.
      placeholder: "e.g., User Story #123"
    validations:
      required: true
