name: "📝 Test Case Template"
description: Detail the steps necessary to perform a specific test case within the OSRD application.
title: "[TEST]"
labels: 
  - kind:test-case
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this test case template!
        Please provide detailed steps and expected outcomes to help ensure thorough testing.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Brief description of what this test case is intended to verify. Include what part of the application it is testing.
      placeholder: "e.g., Ce cas de test vérifie la création d'une étude."
    validations:
      required: true

  - type: textarea
    id: preconditions
    attributes:
      label: Preconditions
      description: |
        List any conditions or setup that must be done before executing this test case.
      placeholder: "e.g., Les points remarquables sont bien importés."
    validations:
      required: false

  - type: textarea
    id: test_data
    attributes:
      label: Test Data
      description: Specify the data values needed for executing this test.
      placeholder: "e.g., Matériel roulant: TGV"
    validations:
      required: false

  - type: textarea
    id: steps_and_results
    attributes:
      label: Steps and Expected Results
      description: |
        Please enter the steps for the test case and their expected results using the markdown table format below. Number each step and clearly specify the expected outcome for each step in the corresponding row. This format helps in organizing the information clearly and makes it more readable for everyone.
        
        **Markdown Table Guide:**
        Use `|` to separate columns and `-` to create headers. An example is provided below.
        
        ```
        | Step | Expected Result |
        |------|-----------------|
        | Step detail here | Expected outcome here |
        ```
        
        Please replace the placeholder content with the specific steps and expected results for your test case.
      placeholder: |
        | Step | Expected Result |
        |------|-----------------|
        | Example: Navigate to the specified section of the application. | The appropriate page or section loads successfully. |
        | Add more rows as needed for each step and its expected result. | Corresponding expected outcome for the step. |
    validations:
      required: true

  - type: textarea
    id: notes
    attributes:
      label: Notes
      description: |
        Any additional information that testers need to know, such as special configurations, environment-specific instructions, etc.
      placeholder: "ex., Assurez-vous d'effacer les cookies avant de commencer le test."
    validations:
      required: false

  - type: textarea
    id: references
    attributes:
      label: References
      description: |
        Links to the related documents, tickets, user stories, etc.
      placeholder: "e.g., User Story #123"
    validations:
      required: true
