name: Playwright Tests

on:
  push:
    branches: [master]

jobs:
  npm-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 16.*

      - name: Build Docker image
        run: docker build . --file Dockerfile -t plimage

      - name: Run Docker container
        run: docker run -d --name plcontainer plimage

      - name: Copy allure-results from container
        run: docker cp plcontainer:/tests/allure-results allure-results
        # Assuming 'sudo' is not required since GitHub Actions runners usually have the necessary permissions

      - name: Upload allure-results artifact
        uses: actions/upload-artifact@v2
        with:
          name: allure-results
          path: allure-results

      - name: Checkout gh-pages branch
        if: always()
        continue-on-error: true
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: gh-pages

      - name: Generate Allure report
        if: always()
        uses: simple-elf/allure-report-action@master
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history

      - name: Deploy to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-history